library(psych)
library(MASS)
library(ggplot2)
attach(wineRaw2)

pdf("univariate_graph.pdf")

#print the histogram (2*2) to show the distribution of the variable values
par(mfrow=c(2,2), oma = c(1,1,0,0) + 0.1, mar = c(3,3,1,1) + 0.1)
barplot((table(quality)), col=c("slateblue4", "slategray", "slategray1", "slategray2", "slategray3", "skyblue4"))
  mtext("Quality", side=1, outer=F, line=2, cex=0.8)
truehist(fixed.acidity, h = 0.5, col="slategray3")
  mtext("Fixed Acidity", side=1, outer=F, line=2, cex=0.8)
truehist(volatile.acidity, h = 0.05, col="slategray3")
  mtext("Volatile Acidity", side=1, outer=F, line=2, cex=0.8)
truehist(citric.acid, h = 0.1, col="slategray3")
  mtext("Citric Acid", side=1, outer=F, line=2, cex=0.8)
truehist(residual.sugar, h = 0.5, col="slategray3")
  mtext("Residual Sugar", side=1, outer=F, line=2, cex=0.8)
truehist(chlorides, h = 0.02, col="slategray3")
  mtext("Chlorides", side=1, outer=F, line=2, cex=0.8)
truehist(free.sulfur.dioxide, h = 3, col="slategray3")
  mtext("Free Sulfur diox", side=1, outer=F, line=2, cex=0.8)
truehist(total.sulfur.dioxide, h = 10, col="slategray3")
  mtext("Total Sulfur diox", side=1, outer=F, line=2, cex=0.8)
truehist(density, h = 0.001, col="slategray3")
  mtext("Density", side=1, outer=F, line=2, cex=0.8)
truehist(pH, h = 0.05, col="slategray3")
  mtext("pH", side=1, outer=F, line=2, cex=0.8)
truehist(sulphates, h = 0.1, col="slategray3")
  mtext("Sulphates", side=1, outer=F, line=2, cex=0.8)
truehist(alcohol, h = 0.5, col="slategray3")
  mtext("Alcohol", side=1, outer=F, line=2, cex=0.8)

#print boxplot (1*6, 1*5) to identify the outliners of the input variables
par(mfrow=c(1,6), oma = c(1,1,0,0) + 0.1,  mar = c(3,3,1,1) + 0.1)
boxplot(fixed.acidity, col="slategray2", pch=19)
  mtext("Fixed Acidity", cex=0.8, side=1, line=2)
boxplot(volatile.acidity, col="slategray2", pch=19)
  mtext("Volatile Acidity", cex=0.8, side=1, line=2)
boxplot(citric.acid, col="slategray2", pch=19)
  mtext("Citric Acid", cex=0.8, side=1, line=2)
boxplot(residual.sugar, col="slategray2", pch=19)
  mtext("Residual Sugar", cex=0.8, side=1, line=2)
boxplot(chlorides, col="slategray2", pch=19)
  mtext("Chlorides", cex=0.8, side=1, line=2)
boxplot(free.sulfur.dioxide, col="slategray2", pch=19)
  mtext("Free Sulfur diox", cex=0.8, side=1, line=2)
par(mfrow=c(1,5), oma = c(1,1,0,0) + 0.1,  mar = c(3,3,1,1) + 0.1)
boxplot(total.sulfur.dioxide, col="slategray2", pch=19)
  mtext("Total Sulfur diox", cex=0.8, side=1, line=2)
boxplot(density, col="slategray2", pch=19)
  mtext("Density", cex=0.8, side=1, line=2)
boxplot(pH, col="slategray2", pch=19)
  mtext("pH", cex=0.8, side=1, line=2)
boxplot(sulphates, col="slategray2", pch=19)
  mtext("Sulphates", cex=0.8, side=1, line=2)
boxplot(alcohol, col="slategray2", pch=19)
  mtext("Alcohol", cex=0.8, side=1, line=2)

pairs(wineRaw2[,-12], gap=0, pch=19, cex=0.4, col="darkblue")

dev.off()

detach(wineRaw2)